# Generated by Django 3.2.1 on 2021-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_merchantuser_is_added_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
